import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Stitch Material Design tokens — "The Digital Blueprint" design system
        "surface":                  "#fdf8f5",
        "surface-bright":           "#fdf8f5",
        "surface-dim":              "#ded9d6",
        "surface-container-lowest": "#ffffff",
        "surface-container-low":    "#f8f3f0",
        "surface-container":        "#f2edea",
        "surface-container-high":   "#ece7e4",
        "surface-container-highest":"#e6e2df",
        "surface-variant":          "#e6e2df",
        "surface-tint":             "#9b4510",
        "on-surface":               "#1c1b1a",
        "on-surface-variant":       "#56433a",
        "inverse-surface":          "#32302e",
        "inverse-on-surface":       "#f5f0ed",
        "background":               "#fdf8f5",
        "on-background":            "#1c1b1a",
        "primary":                  "#9b4510",
        "primary-container":        "#dd7740",
        "primary-fixed":            "#ffdbcb",
        "primary-fixed-dim":        "#ffb692",
        "on-primary":               "#ffffff",
        "on-primary-container":     "#4e1c00",
        "on-primary-fixed":         "#341100",
        "on-primary-fixed-variant": "#793000",
        "inverse-primary":          "#ffb692",
        "secondary":                "#586062",
        "secondary-container":      "#dae1e3",
        "secondary-fixed":          "#dde4e6",
        "secondary-fixed-dim":      "#c1c8ca",
        "on-secondary":             "#ffffff",
        "on-secondary-container":   "#5d6466",
        "on-secondary-fixed":       "#161d1f",
        "on-secondary-fixed-variant":"#41484a",
        "tertiary":                 "#875133",
        "tertiary-container":       "#c38462",
        "tertiary-fixed":           "#ffdbca",
        "tertiary-fixed-dim":       "#feb691",
        "on-tertiary":              "#ffffff",
        "on-tertiary-container":    "#492006",
        "on-tertiary-fixed":        "#331100",
        "on-tertiary-fixed-variant":"#6b3a1e",
        "outline":                  "#897268",
        "outline-variant":          "#dcc1b5",
        "error":                    "#ba1a1a",
        "error-container":          "#ffdad6",
        "on-error":                 "#ffffff",
        "on-error-container":       "#93000a",
        // Legacy brand palette (used in older pages, keeping for compatibility)
        brand: {
          50:  "#FEF0EC",
          100: "#FDDDD2",
          200: "#FBBBA4",
          300: "#F8907A",
          400: "#F36D4C",
          500: "#E8572E",
          600: "#D85A30",
          700: "#B84828",
          800: "#92381E",
          900: "#6B2913",
          950: "#451A0A",
        },
        accent: {
          50:  "#FFFBEB",
          100: "#FEF3C7",
          200: "#FDE68A",
          300: "#FCD34D",
          400: "#FBBF24",
          500: "#F59E0B",
          600: "#D97706",
          700: "#B45309",
          800: "#92400E",
          900: "#78350F",
        },
        dark: {
          50:  "#3D1509",
          100: "#5C2214",
          200: "#7A3828",
          300: "#98584A",
          400: "#B07868",
          500: "#C49890",
          600: "#D8BAB5",
          700: "#E8D5D0",
          800: "#F5ECE8",
          900: "#FAF4F1",
          950: "#FFFAF8",
        },
      },
      fontFamily: {
        headline: ["var(--font-space-grotesk)", "Space Grotesk", "sans-serif"],
        body:     ["var(--font-inter)", "Inter", "sans-serif"],
        label:    ["var(--font-space-grotesk)", "Space Grotesk", "sans-serif"],
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":  "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
        "hero-gradient":   "linear-gradient(135deg, #fdf8f5 0%, #f8f3f0 50%, #fdf8f5 100%)",
        "cta-gradient":    "linear-gradient(135deg, #9b4510, #dd7740)",
      },
      animation: {
        "fade-in":    "fadeIn 0.5s ease-in-out",
        "slide-up":   "slideUp 0.4s ease-out",
        "pulse-slow": "pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
      keyframes: {
        fadeIn: {
          "0%":   { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%":   { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
    },
  },
  plugins: [require("@tailwindcss/typography")],
};

export default config;