import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Agency Dossier retint — Material D3 token NAMES retained for zero-touch ripple,
        // values remapped to paper/ink/oxide/foil palette.
        "surface":                  "#f2ebdc",
        "surface-bright":           "#f7f1e4",
        "surface-dim":              "#e2d9c1",
        "surface-container-lowest": "#f7f1e4",
        "surface-container-low":    "#f2ebdc",
        "surface-container":        "#e8dfc8",
        "surface-container-high":   "#ddd3b8",
        "surface-container-highest":"#d4caba",
        "surface-variant":          "#e8dfc8",
        "surface-tint":             "#9e2a2b",
        "on-surface":               "#0f0e0c",
        "on-surface-variant":       "#3a342a",
        "inverse-surface":          "#0f0e0c",
        "inverse-on-surface":       "#f2ebdc",
        "background":               "#f2ebdc",
        "on-background":            "#0f0e0c",
        "primary":                  "#9e2a2b",
        "primary-container":        "#6d1b1c",
        "primary-fixed":            "#f2ebdc",
        "primary-fixed-dim":        "#b8935a",
        "on-primary":               "#f2ebdc",
        "on-primary-container":     "#f2ebdc",
        "on-primary-fixed":         "#0f0e0c",
        "on-primary-fixed-variant": "#6d1b1c",
        "inverse-primary":          "#b8935a",
        "secondary":                "#3a342a",
        "secondary-container":      "#e8dfc8",
        "secondary-fixed":          "#e8dfc8",
        "secondary-fixed-dim":      "#b8935a",
        "on-secondary":             "#f2ebdc",
        "on-secondary-container":   "#0f0e0c",
        "on-secondary-fixed":       "#0f0e0c",
        "on-secondary-fixed-variant":"#3a342a",
        "tertiary":                 "#6b6357",
        "tertiary-container":       "#b8935a",
        "tertiary-fixed":           "#e8dfc8",
        "tertiary-fixed-dim":       "#b8935a",
        "on-tertiary":              "#f2ebdc",
        "on-tertiary-container":    "#0f0e0c",
        "on-tertiary-fixed":        "#0f0e0c",
        "on-tertiary-fixed-variant":"#3a342a",
        "outline":                  "#3a342a",
        "outline-variant":          "#d4caba",
        "error":                    "#9e2a2b",
        "error-container":          "#e8dfc8",
        "on-error":                 "#f2ebdc",
        "on-error-container":       "#6d1b1c",
        // Legacy brand palette (used in older pages, keeping for compatibility)
        brand: {
          50:  "#FEF0EC",
          100: "#FDDDD2",
          200: "#FBBBA4",
          300: "#F8907A",
          400: "#F36D4C",
          500: "#E8572E",
          600: "#D85A30",
          700: "#B84828",
          800: "#92381E",
          900: "#6B2913",
          950: "#451A0A",
        },
        accent: {
          50:  "#FFFBEB",
          100: "#FEF3C7",
          200: "#FDE68A",
          300: "#FCD34D",
          400: "#FBBF24",
          500: "#F59E0B",
          600: "#D97706",
          700: "#B45309",
          800: "#92400E",
          900: "#78350F",
        },
        dark: {
          50:  "#3D1509",
          100: "#5C2214",
          200: "#7A3828",
          300: "#98584A",
          400: "#B07868",
          500: "#C49890",
          600: "#D8BAB5",
          700: "#E8D5D0",
          800: "#F5ECE8",
          900: "#FAF4F1",
          950: "#FFFAF8",
        },
        "paper":      "#f2ebdc",
        "paper-deep": "#e8dfc8",
        "paper-fade": "#f7f1e4",
        "ink":        "#0f0e0c",
        "ink-soft":   "#3a342a",
        "ink-fade":   "#6b6357",
        "oxide":      "#9e2a2b",
        "oxide-deep": "#6d1b1c",
        "foil":       "#b8935a",
      },
      fontFamily: {
        headline: ["var(--font-fraunces)", "Fraunces", "Georgia", "serif"],
        body:     ["var(--font-newsreader)", "Newsreader", "Georgia", "serif"],
        label:    ["var(--font-plex-mono)", "IBM Plex Mono", "ui-monospace", "monospace"],
        mono:     ["var(--font-plex-mono)", "IBM Plex Mono", "ui-monospace", "monospace"],
        accent:   ["var(--font-instrument-serif)", "Instrument Serif", "serif"],
        display:  ["var(--font-fraunces)", "Fraunces", "Georgia", "serif"],
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":  "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
        "hero-gradient":   "linear-gradient(135deg, #fdf8f5 0%, #f8f3f0 50%, #fdf8f5 100%)",
        "cta-gradient":    "linear-gradient(135deg, #9b4510, #dd7740)",
      },
      animation: {
        "fade-in":    "fadeIn 0.5s ease-in-out",
        "slide-up":   "slideUp 0.4s ease-out",
        "pulse-slow": "pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "hero-1":     "fadeSlideUp 0.6s ease-out 0.1s both",
        "hero-2":     "fadeSlideUp 0.6s ease-out 0.25s both",
        "hero-3":     "fadeSlideUp 0.6s ease-out 0.4s both",
        "hero-4":     "fadeSlideUp 0.6s ease-out 0.55s both",
        "hero-5":     "fadeSlideUp 0.8s ease-out 0.5s both",
        "progress-loop": "progressLoop 4s ease-in-out infinite",
      },
      keyframes: {
        fadeIn: {
          "0%":   { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%":   { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        fadeSlideUp: {
          "0%":   { opacity: "0", transform: "translateY(24px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        progressLoop: {
          "0%, 100%": { width: "38%" },
          "50%":      { width: "72%" },
        },
      },
    },
  },
  plugins: [require("@tailwindcss/typography")],
};

export default config;